//Celeste Soto Valdebenito
//Solange Soto Broock
//Alex Sanchez Carrillo
//Brian Sobarzo Benavente
//Javier Torres Rios
package vista;

import dao.ProductoDAO;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author celes
 */
public class VistaProducto extends javax.swing.JFrame {

    DefaultTableModel modelo;
    TableRowSorter<DefaultTableModel> sorter;

    /**
     * Creates new form VistaProducto
     */
    public VistaProducto() {
    
        initComponents();
        setLocationRelativeTo(null);
        
        modelo = new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Codigo");
        modelo.addColumn("Precio(en pesos)");
        modelo.addColumn("Descripcion");
        

        this.jTable1.setModel(modelo);
        jTable1.setAutoCreateRowSorter(true);
        sorter = new TableRowSorter<>(modelo);
        jTable1.setRowSorter(sorter);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        modificar2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setForeground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("Inventario");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 10, 180, 30);

        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 60, 50, 16);

        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Código:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 90, 50, 20);

        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Precio:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 120, 50, 30);

        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("Descripción:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 160, 80, 16);

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(110, 60, 100, 28);

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(110, 90, 100, 28);

        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField3);
        jTextField3.setBounds(110, 120, 100, 28);

        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField4);
        jTextField4.setBounds(110, 150, 200, 60);

        jButton1.setText("Ingresar Producto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 220, 140, 28);

        jButton2.setText("Eliminar Producto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(170, 220, 140, 28);

        jButton3.setText("Eliminar todo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(320, 220, 130, 28);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 260, 560, 200);

        jButton5.setText("Volver");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(500, 470, 73, 28);

        modificar2.setText(" Modificar");
        modificar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar2ActionPerformed(evt);
            }
        });
        jPanel1.add(modificar2);
        modificar2.setBounds(410, 90, 100, 28);

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(270, 50, 260, 30);

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(270, 70, 200, 0);

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jLabel8);
        jLabel8.setBounds(270, 80, 140, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 660, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String n = jTextField1.getText();
        String c = jTextField2.getText();
        String p = jTextField3.getText();
        String d = jTextField4.getText();
        if (n.equals("") || c.equals("")|| p.equals("")|| d.equals("")) {
        JOptionPane.showMessageDialog(this, "Uno o más campos están vacíos. Llene todos los datos del producto para agregar");} else {
        ProductoDAO pd = new ProductoDAO();
        
        pd.insertarDatos(this.jTextField1.getText(), this.jTextField2.getText(), Integer.parseInt(this.jTextField3.getText()), this.jTextField4.getText());
        String[] Datos = new String[5];
        Datos[0] = jTextField1.getText();
        jTextField1.setText(null);
        Datos[1] = jTextField2.getText();
        jTextField2.setText(null);
        Datos[2] = jTextField3.getText();
        jTextField3.setText(null);
        Datos[3] = jTextField4.getText();
        jTextField4.setText(null);
        modelo.addRow(Datos);
        JOptionPane.showMessageDialog(this, "Ha ingresado un producto correctamente.");
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      String codigo = jTable1.getValueAt(jTable1.getSelectedRow(),1).toString();
        ProductoDAO pd = new ProductoDAO();
        pd.eliminarDatos(codigo);
        int filaseleccionada= jTable1.getSelectedRow();
        if (filaseleccionada>=0){
            modelo.removeRow(filaseleccionada);
            JOptionPane.showMessageDialog(this, "El producto seleccionado ha sido eliminado correctamente.");
        }
        else {
            JOptionPane.showMessageDialog(null,"Tabla vacía o no seleccionó fila");
        
        }
    
        
        if (filaseleccionada >= 0) {
            modelo.removeRow(filaseleccionada);
        } else {
            JOptionPane.showMessageDialog(null, "Tabla vacía o no seleccionó fila");
            
        } 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ProductoDAO pd= new ProductoDAO();
        pd.eliminarTodo();
        int cantidadfilas = jTable1.getRowCount();
        for (int i = cantidadfilas - 1; i >= 0; i--) {
            modelo.removeRow(i);
            if( i == 0){
            JOptionPane.showMessageDialog(this, "Se han borrado todos los productos.");
        }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         VistaLogin ventana = new VistaLogin();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void modificar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar2ActionPerformed
       int filaseleccionada = jTable1.getSelectedRow();
       String n = jTextField1.getText();
        String c = jTextField2.getText();
        String p = jTextField3.getText();
        String d = jTextField4.getText();
        if (n.equals("") || c.equals("")|| p.equals("")|| d.equals("")) {
        JOptionPane.showMessageDialog(this, "Campos vacios, rellene todos los datos y presione el producto a modificar");} else {
            if(Integer.parseInt(jTextField3.getText()) >=0){
           ProductoDAO pd = new ProductoDAO();
   
        String valor = jTable1.getValueAt(filaseleccionada, 1).toString();
        if (filaseleccionada >= 0) {
            if (pd.eliminarDatos(valor)) {
                modelo.removeRow(filaseleccionada);
                pd.insertarDatos(this.jTextField1.getText(), this.jTextField2.getText(), Integer.parseInt(this.jTextField3.getText()), this.jTextField4.getText());
                String[] Datos = new String[5];
                Datos[0] = jTextField1.getText();
                jTextField1.setText(null);
                Datos[1] = jTextField2.getText();
                jTextField2.setText(null);
                Datos[2] = jTextField3.getText();
                jTextField3.setText(null);
                Datos[3] = jTextField4.getText();
                jTextField4.setText(null);
                modelo.addRow(Datos);
                JOptionPane.showMessageDialog(this, "Se ha modificado el producto seleccionado :).");
            }else {JOptionPane.showMessageDialog(this, "Precio inexistente, modifiquelo.");}
            }
        }
        }
    }//GEN-LAST:event_modificar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton modificar2;
    // End of variables declaration//GEN-END:variables
}
